region_file:
  class: File
  path: /home/wotromp/InterTwin/workflow_refactor/model_setup/HumberDelta_large.geojson
script_setup_sfincs:
  class: File
  path: ./pyscripts/setup_sfincs.py
sf_res: 100
sf_subgrid_pixels: 6
script_setup_wflow:
  class: File
  path: ./pyscripts/setup_wflow.py
script_setup_ra2ce:
  class: File
  path: ./pyscripts/setup_ra2ce.py
script_build_ra2ce:
  class: File
  path: ./pyscripts/build_ra2ce.py
script_setup_fiat:
  class: File
  path: ./pyscripts/setup_fiat.py
script_oscar:
  class: File
  path: ./pyscripts/oscar.py
endpoint: 'https://oscar-ukri.intertwin.fedcloud.eu'
refreshtoken: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI0ZmM3MDMxNC0wODQ5LTRkZGQtYjgxNy1jNzAxZTg4MTdhYzgifQ.eyJleHAiOjE3ODc4MTY1MzcsImlhdCI6MTc1MzY5MzQ1OSwianRpIjoiMzNhYWRjNmYtYmUzNS00ZTJhLTkyNGUtYzkwYWFlZTEzZDEzIiwiaXNzIjoiaHR0cHM6Ly9hYWktZGVtby5lZ2kuZXUvYXV0aC9yZWFsbXMvZWdpIiwiYXVkIjoiaHR0cHM6Ly9hYWktZGVtby5lZ2kuZXUvYXV0aC9yZWFsbXMvZWdpIiwic3ViIjoiMzg2Mjg1NWM0MzdlYWMwZjhlOTAxMjk4MDQ0YzE3YTg0Mzc4M2Y0YThhNzM5MjYzNWI1NjcwODUzOTcyNTJlZEBlZ2kuZXUiLCJ0eXAiOiJPZmZsaW5lIiwiYXpwIjoidG9rZW4tcG9ydGFsIiwibm9uY2UiOiIwZWFhZmFlNTU0ZTU0Y2UyNzkyODkxOTgxZTZiNmY0YSIsInNlc3Npb25fc3RhdGUiOiI2NmNhZTRmNy1hMmE1LTRmNjctYjA5My0yYmQxMjE3ZDBlNDQiLCJzY29wZSI6Im9wZW5pZCB2b3BlcnNvbl9leHRlcm5hbF9hZmZpbGlhdGlvbiBvZmZsaW5lX2FjY2VzcyBlZHVwZXJzb25fZW50aXRsZW1lbnQgZW50aXRsZW1lbnRzIHZvcGVyc29uX2lkIHByb2ZpbGUgZW1haWwiLCJzaWQiOiI2NmNhZTRmNy1hMmE1LTRmNjctYjA5My0yYmQxMjE3ZDBlNDQifQ.9eEQ6EftcZgN5ftKCK53658drZtLiRK7wTLgrhixNEg
service_ra2ce: ra2ce
service_directory:
  class: Directory
  path: ./oscar_services/
oscar_output: output
