fa_database:
  class: Directory
  path: "../../FloodAdapt_database/Humber/"
scenario: "Empty_Event_current_no_measures"
sfincs_update_script:
  class: File
  path: "../pyscripts/update_sfincs.py"
arrange_script:
  class: File
  path: "../pyscripts/arrange_fa_folders.py"