name: sfincs_gfm
channels:
  - conda-forge

dependencies:
  - geoviews
  - hvplot
  - ipykernel
  - jupyter_bokeh
  - dask=2025.2.0
  - python=3.10.*
  - traitlets=5.14.3
  - pip
  - pip:
    - git+https://github.com/TUW-GEO/dask-flood-mapper
    - -e .